### ISSUE TITLE
Can I use deepQM for calculating binding affinity of protein protein interaction

### ISSUE THREAD

**Issue by narubi2** [otayfuroglu/deepQM#2]
Hi,

Thanks for sharing deepQM.
I'm curious if it's okay to use deepQM to calculate PPI binding affinity.

Thanks.

**Comment by otayfuroglu** [comment]
Hi Nurabi,
Thank you very much for your interest.
We are currently testing it and benchmarking against mmpbsa. Our preliminary work shows it gives high correlation to mmpbsa results and somewhat good results to experimental values. We will be submitting the results within a couple of months.

As long as properly indexed, it could be used for peptides or proteins. However one should keep in mind that highly charged interactions and long range interactions are not covered by ANI.

Best
Omer
